// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAueAq2tTunIBOz6XMmmTxgH7FahWEKGEg',
    appId: '1:762777123695:web:ca8fbdf32a34febfe8069a',
    messagingSenderId: '762777123695',
    projectId: 'water-reminder-app-1',
    authDomain: 'water-reminder-app-1.firebaseapp.com',
    storageBucket: 'water-reminder-app-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB250WmhcWhQN9PZLxoJUw5n6fBKOQpnHs',
    appId: '1:762777123695:android:2b50ccf210a90fa4e8069a',
    messagingSenderId: '762777123695',
    projectId: 'water-reminder-app-1',
    storageBucket: 'water-reminder-app-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_ls3ofLIZQdWpIr6IYKFCFjhTiNfhEGU',
    appId: '1:762777123695:ios:881743bb426c2391e8069a',
    messagingSenderId: '762777123695',
    projectId: 'water-reminder-app-1',
    storageBucket: 'water-reminder-app-1.appspot.com',
    iosClientId: '762777123695-9pqf2hm6vn3hof1jmf7u1lf5gcbtrhdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_ls3ofLIZQdWpIr6IYKFCFjhTiNfhEGU',
    appId: '1:762777123695:ios:881743bb426c2391e8069a',
    messagingSenderId: '762777123695',
    projectId: 'water-reminder-app-1',
    storageBucket: 'water-reminder-app-1.appspot.com',
    iosClientId: '762777123695-9pqf2hm6vn3hof1jmf7u1lf5gcbtrhdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.waterReminder',
  );
}
